### ISSUE TITLE
Need more options

### ISSUE THREAD

**Issue by tctctctc** [dolsup/fontler#1]
Hello.
I was looking for sfntly, and found that it contains sfnttool.jar. sfnttool.jar has more options available, not only -s, -e and -w 
Like:
-x Enable Microtype Express compression for EOT format
-h,-hints Strip hints
-x -n work together
So it could replace lib in your code, without breaking current code and let you add more options

**Comment by dolsup** [comment]
Hello, tctctctc!

Thank you for your suggestion.
I added more options(x, h) and updated other parts, so it works well now.

**Comment by tctctctc** [comment]
Thank you. Here is another interesting code from google. https://github.com/google/woff2.git it is use Brotli byte-level compression algorithm to generate woff2 files. And my tests show great result in font size it's generate.

**Comment by dolsup** [comment]
Thank you for the useful information!
I added new option for woff2 with [a node.js wrapper for google/woff2](https://www.npmjs.com/package/ttf2woff2).
